name: learn-github-actions
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - name: Write report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Post reports as comments in GitHub PRs
          cat results.txt >> "File uploaded
          cml-send-comment report.md
